[package]
name = "cashu-crab"
version = "0.1.0"
edition = "2021"
authors = ["thesimplekid"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/thesimplekid/cashu-crab"
description = "Cashu rust wallet library"
exclude = ["integration_test"]

[workspace]
members = ["integration_test"]


[dependencies]
base64 = "0.21.0"
bitcoin = { version = "0.30.0", features=["serde"] }
bitcoin_hashes = "0.12.0"
hex = "0.4.3"
k256 = { version = "0.13.1", features=["arithmetic"] }
lightning-invoice = { version = "0.23.0", features=["serde"] }
minreq = { version = "2.7.0", features = ["json-using-serde", "https"] }
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1.0.160", features = ["derive"]}
serde_json = "1.0.96"
url = "2.3.1"

[dev-dependencies]
tokio = {version = "1.27.0", features = ["rt", "macros"] }
