[workspace]
members = [
    "crates/cdk",
]
resolver = "2"

[workspace.package]
license = "BSD-3-Clause"
homepage = "https://github.com/thesimplekid/cashu-crab"
repository = "https://github.com/thesimplekid/cashu-crab.git"
rust-version = "1.70.0" # MSRV

[workspace.metadata]
authors = ["thesimplekid"]
edition = "2021"
description = "cashu-crab"
readme = "README.md"
repository = "https://github.com/thesimplekid/cashu-crab"
license-file = "LICENSE"
keywords = ["bitcoin", "e-cash", "cashu"]

[workspace.dependencies]
tokio = { version = "1.32", default-features = false }

[profile]

[profile.ci]
inherits = "dev"
incremental = false
debug = "line-tables-only"
lto = "off"
