[package]
name = "cashu-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["integration_test"]


[dependencies]
minreq = { version = "2.7.0", features = ["json-using-serde", "https"] }
serde = { version = "1.0.160", features = ["derive"]}
thiserror = "1.0.40"
url = "2.3.1"
