[package]
name = "cashu-rs"
version = "0.1.0"
edition = "2021"
authors = ["thesimplekid"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/thesimplekid/cashu-rs"
description = "Cashu rust library"


[dependencies]
base64 = "0.21.0"
bitcoin = { version = "0.30.0", features=["serde"] }
bitcoin_hashes = "0.12.0"
hex = "0.4.3"
lightning-invoice = { version = "0.22.0", features=["serde"] }
minreq = { version = "2.7.0", features = ["json-using-serde", "https"] }
rand = "0.8.5"
secp256k1 = { version = "0.27.0", features = ["rand-std", "bitcoin-hashes-std"] }
serde = { version = "1.0.160", features = ["derive"]}
serde_json = "1.0.96"
thiserror = "1.0.40"
url = "2.3.1"

[dev-dependencies]
tokio = {version = "1.27.0", features = ["rt", "macros"] }
