[workspace]
members = [
    "crates/cdk",
]
resolver = "2"

[workspace.package]
license = "MIT"
homepage = "https://github.com/cashu/cdk"
repository = "https://github.com/cashu/cdk.git"
rust-version = "1.70.0" # MSRV

[workspace.metadata]
authors = ["CDK Developers"]
edition = "2021"
description = "Cashu Development Kit"
readme = "README.md"
repository = "https://github.com/cashu/cdk"
license-file = "LICENSE"
keywords = ["bitcoin", "e-cash", "cashu"]

[workspace.dependencies]
tokio = { version = "1.32", default-features = false }

[profile]

[profile.ci]
inherits = "dev"
incremental = false
debug = "line-tables-only"
lto = "off"
