[package]
name = "cdk-fake-wallet"
version = "0.4.0"
edition = "2021"
authors = ["CDK Developers"]
license = "MIT"
homepage = "https://github.com/cashubtc/cdk"
repository = "https://github.com/cashubtc/cdk.git"
rust-version = "1.63.0" # MSRV
description = "CDK fake ln backend"

[dependencies]
async-trait = "0.1.74"
bitcoin = { version = "0.30", default-features = false } # lightning-invoice uses v0.30
cdk = { path = "../cdk", version = "0.4.0", default-features = false, features = ["mint"] }
futures = { version = "0.3.28", default-features = false }
tokio = { version = "1", default-features = false }
tracing = { version = "0.1", default-features = false, features = ["attributes", "log"] }
thiserror = "1"
uuid = { version = "1", features = ["v4"] }
lightning-invoice = { version = "0.31", features = ["serde"] }
lightning = "0.0.123"
tokio-stream = "0.1.15"
rand = "0.8.5"
