[package]
name = "cdk-redb"
version = "0.1.0"
edition = "2021"
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
cdk.workspace = true
redb = "2.0.0"
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde_json = "1.0.96"
