name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - version: stable
        build-args:
          [
            -p cashu,
            -p cashu --no-default-features,
            -p cashu --no-default-features --features wallet,
            -p cashu --no-default-features --features mint,
            -p cashu-sdk,
            -p cashu-sdk --no-default-features,
            -p cashu-sdk --features blocking,
          ]
    steps:
    - name: Checkout Crate
      uses: actions/checkout@v3
    - name: Set Toolchain
      # https://github.com/dtolnay/rust-toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Set default toolchain
      run: rustup default ${{ matrix.rust.version }}
    - name: Test
      run: |
        rustup 
        cargo test ${{ matrix.build-arfgs }} 
